### ISSUE TITLE
Error: Expected [\n\r] but end of input found. 

### ISSUE THREAD

**Issue by annelorraineuy** [react-native-community/react-native-linear-gradient#141]
```
rnpm-install info Linking react-native-linear-gradient android dependency 
rnpm-install info Android module react-native-linear-gradient has been successfully linked 
rnpm-install ERR! It seems something went wrong while linking. Error: Expected [\n\r] but end of input found.
Please file an issue here: https://github.com/facebook/react-native/issues 
```

I get this error after doing `react-native link react-native-linear-gradient`

```
package:
"react": "15.4.1",
"react-native": "^0.39.2"
```

**Comment by annelorraineuy** [comment]
I got this to work now.

This happens when you try to `react-native link` the latest code when your react-native is still at 0.39. So I forked my own copy of the repo and reverted to the commit before the RN 0.40 update.

**Comment by dgladkov** [comment]
Glad to know that the issue is resolved! Closing it.

**Comment by WhynoChinese** [comment]
I still have this problem, I try to react-native link and my react-native is 0.43

**Comment by master-atul** [comment]
I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

**Comment by vantuan88291** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

very nice, i solved this stupid error just one line :D

**Comment by LeslieJAnderson** [comment]
@master-atul, you solved my problem for a completely different library. Thank you.

**Comment by matthew-gordon** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This solved an the issue for me as well for anyone coming across this in 2020

**Comment by GermainPereira** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Worked for me :laughing: :laughing:

```
    "react": "16.13.1",
    "react-native": "0.63.0",
```

**Comment by SrBrahma** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

React Native should fix it.

**Comment by Jhoy1992** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This solved my problem when trying to link custom fonts, thanks man.

**Comment by Paulotx** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Tank you

**Comment by gabrielkesslau** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Thanks!!

**Comment by carlomigueldy** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

I wonder how you figured this out XD But thanks man!!

**Comment by guimaraesmiguel** [comment]
> > I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `
> 
> I wonder how you figured this out XD But thanks man!!

I got the same issue and it solved my life, but I have the same question mark: how you figured this out. Any way, thank you very much.

**Comment by ricardopontesdantas** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Thanks!!

**Comment by lmourabraga** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

This is the kind of problem we don't know why but we also don't care. Thank you for sharing the solution. :) 💯

**Comment by PrantikMondal** [comment]
> I solved it by adding a new line to end of `ios/[Project].xcodeproj/project.pbxproj `

Not worked for me at all. 
If i tried to link any of library to my project, my error showing something like this:

error Linking "@sentry/react-native" failed. Run CLI with --verbose flag for more details.
SyntaxError: Expected "{" but end of input found.
    at peg$buildStructuredError (C:\[Project_name]\node_modules\xcode\lib\parser\pbxproj.js:429:12)
    at Object.peg$parse [as parse] (C:\[Project_name]\node_modules\xcode\lib\parser\pbxproj.js:1891:11)
    at pbxProject.parseSync (C:\[Project_name]\node_modules\xcode\lib\pbxProject.js:63:24)
    at isInstalled (C:\[Project_name]\node_modules\@react-native-community\cli-platform-ios\build\link\isInstalled.js:43:67)
    at Object.isInstalled (C:\[Project_name]\node_modules\@react-native-community\cli-platform-ios\build\link\common\isInstalled.js:23:35)
    at Object.keys.forEach.platform (C:\[Project_name]\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:53:36)
    at Array.forEach (<anonymous>)
    at linkDependency (C:\[Project_name]\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:36:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by xialGuri** [comment]
@PrantikMondal did you solve that problem? adding a  line didn't work for me neither
